[2025-03-04T07:14:57.907+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T07:14:58.069+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_data_pipeline.fact_processing scheduled__2020-08-01T00:00:00+00:00 [queued]>
[2025-03-04T07:14:58.080+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_data_pipeline.fact_processing scheduled__2020-08-01T00:00:00+00:00 [queued]>
[2025-03-04T07:14:58.092+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-04T07:14:58.103+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fact_processing> on 2020-08-01 00:00:00+00:00
[2025-03-04T07:14:58.110+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-04T07:14:58.112+0000] {standard_task_runner.py:72} INFO - Started process 1177 to run task
[2025-03-04T07:14:58.112+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'snowflake_data_pipeline', 'fact_processing', 'scheduled__2020-08-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpf811floh']
[2025-03-04T07:14:58.116+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask fact_processing
[2025-03-04T07:14:58.127+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-04T07:14:58.163+0000] {task_command.py:467} INFO - Running <TaskInstance: snowflake_data_pipeline.fact_processing scheduled__2020-08-01T00:00:00+00:00 [running]> on host 8b83efa08de4
[2025-03-04T07:14:58.164+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  if conf.get("database", "sql_alchemy_conn") == "none://":

[2025-03-04T07:14:58.251+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='snowflake_data_pipeline' AIRFLOW_CTX_TASK_ID='fact_processing' AIRFLOW_CTX_EXECUTION_DATE='2020-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-08-01T00:00:00+00:00'
[2025-03-04T07:14:58.253+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-04T07:14:58.254+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-04T07:14:58.256+0000] {logging_mixin.py:190} INFO - Current task name:fact_processing state:running start_date:2025-03-04 07:14:58.071023+00:00
[2025-03-04T07:14:58.257+0000] {logging_mixin.py:190} INFO - Dag name:snowflake_data_pipeline and current dag run status:running
[2025-03-04T07:14:58.258+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T07:14:58.259+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-04T07:14:58.260+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --models facts --profiles-dir .']
[2025-03-04T07:14:58.271+0000] {subprocess.py:99} INFO - Output:
[2025-03-04T07:15:00.408+0000] {subprocess.py:106} INFO - [0m07:15:00  Running with dbt=1.9.2
[2025-03-04T07:15:01.648+0000] {subprocess.py:106} INFO - [0m07:15:01  Registered adapter: snowflake=1.9.1
[2025-03-04T07:15:03.720+0000] {subprocess.py:106} INFO - [0m07:15:03  Found 5 models, 8 data tests, 5 sources, 589 macros
[2025-03-04T07:15:03.725+0000] {subprocess.py:106} INFO - [0m07:15:03
[2025-03-04T07:15:03.726+0000] {subprocess.py:106} INFO - [0m07:15:03  Concurrency: 10 threads (target='dev')
[2025-03-04T07:15:03.727+0000] {subprocess.py:106} INFO - [0m07:15:03
[2025-03-04T07:15:05.318+0000] {subprocess.py:106} INFO - [0m07:15:05  1 of 1 START sql incremental model curated.fact_orders ......................... [RUN]
[2025-03-04T07:15:08.080+0000] {subprocess.py:106} INFO - [0m07:15:08  1 of 1 OK created sql incremental model curated.fact_orders .................... [[32mSUCCESS 1[0m in 2.76s]
[2025-03-04T07:15:08.487+0000] {subprocess.py:106} INFO - [0m07:15:08
[2025-03-04T07:15:08.489+0000] {subprocess.py:106} INFO - [0m07:15:08  Finished running 1 incremental model in 0 hours 0 minutes and 4.76 seconds (4.76s).
[2025-03-04T07:15:08.619+0000] {subprocess.py:106} INFO - [0m07:15:08
[2025-03-04T07:15:08.621+0000] {subprocess.py:106} INFO - [0m07:15:08  [32mCompleted successfully[0m
[2025-03-04T07:15:08.622+0000] {subprocess.py:106} INFO - [0m07:15:08
[2025-03-04T07:15:08.623+0000] {subprocess.py:106} INFO - [0m07:15:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-04T07:15:09.947+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-04T07:15:09.966+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T07:15:09.967+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=snowflake_data_pipeline, task_id=fact_processing, run_id=scheduled__2020-08-01T00:00:00+00:00, execution_date=20200801T000000, start_date=20250304T071458, end_date=20250304T071509
[2025-03-04T07:15:09.985+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-04T07:15:09.987+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-04T07:15:09.990+0000] {logging_mixin.py:190} INFO - Dag name:snowflake_data_pipeline queued_at:2025-03-04 07:14:24.731448+00:00
[2025-03-04T07:15:09.991+0000] {logging_mixin.py:190} INFO - Task hostname:8b83efa08de4 operator:BashOperator
[2025-03-04T07:15:10.009+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T07:15:10.022+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T07:15:10.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
